conky.config = {
    alignment = 'middle_right',
    background = true,
    update_interval = 1,

    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    double_buffer = true,

    use_xft = true,
    font = 'JetBrainsMono Nerd Font:size=11',

    default_color = '#cdd6f4',

    gap_x = 20,
    gap_y = 20,
};

conky.text = [[
${color #8aadf4}${font JetBrainsMono Nerd Font:bold:size=16}${alignc}◢ SYSTEM ◣
${color #7dc4e4}${hr 2}

${voffset 10}
${color #b7bdf8}${alignc}CPU ${cpu}%
${color #8aadf4}${alignc}${cpubar 8,200}
${color #6e738d}${alignc}${cpugraph 25,200}
${voffset -25}${color #7dc4e4}${alignc}${cpugraph 25,200}

${voffset 12}
${color #b7bdf8}${alignc}RAM ${memperc}%
${color #8aadf4}${alignc}${membar 8,200}
${color #6e738d}${alignc}${memgraph 25,200}
${voffset -25}${color #7dc4e4}${alignc}${memgraph 25,200}

${voffset 15}
${color #b7bdf8}${alignc}DISK ${fs_used /}
${color #8aadf4}${alignc}${fs_bar 8,200 /}

${voffset 20}
${color #8aadf4}${font JetBrainsMono Nerd Font:bold:size=16}${alignc}◢ TIME ◣
${color #7dc4e4}${hr 2}

${voffset 10}
${alignc}${font JetBrainsMono Nerd Font:bold:size=28}${time %H:%M:%S}
${alignc}${color #7dc4e4}${time %A}
]];





